# Generated by Django 3.0.3 on 2020-03-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
